sudo: required

services:
  - docker

before_install:
  - docker build -t ui-test -f ./ui/Dockerfile.dev ./ui

script:
  - docker run -e CI=true ui-test npm test -- --coverage

after_success:
  - docker build -t $DOCKER_ID/fibonacci-ui ./ui
  - docker build -t $DOCKER_ID/fibonacci-api ./api
  - docker build -t $DOCKER_ID/fibonacci-worker ./worker
  - docker build -t $DOCKER_ID/fibonacci-nginx ./nginx
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push $DOCKER_ID/fibonacci-ui
  - docker push $DOCKER_ID/fibonacci-api
  - docker push $DOCKER_ID/fibonacci-worker
  - docker push $DOCKER_ID/fibonacci-nginx